name: Pull requests

on: pull_request

jobs:
  publish:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]
        package: [oidc]

    steps:
      # Setup
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache Node.js modules
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-
            ${{ runner.OS }}-
      - name: Install Dependencies
        run: npm ci --loglevel=error

      # Build
      - name: Build Package
        run: npm run build -- ${{ matrix.package }}
      - name: Upload Artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          name: '${{ matrix.package }}'
          path: './dist/libs/${{ matrix.package }}'
